name: traefik_proxy

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik_public"
      - "--entrypoints.web.address=:80"
      - "--log.level=INFO"
    ports:
      - "80:80"       # Entry point semua traffic dari cloudflared
      - "8090:8080"   # Traefik Dashboard (opsional, bisa dimatikan)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik_public

networks:
  traefik_public:
    name: traefik_public
    driver: bridge
